### ISSUE TITLE
Doesn't persist settings.

### ISSUE THREAD

**Issue by kndgs** [dev47apps/droidcam#206]
I've tried to install both versions (github+regual v4l2 and aur+v4l2-dc). None of them remember my exposure if I am connected with USB. EL button is shown as active but it doesn't work after restart until I turn it off and on again. Manual exposure correction settings in iOS app itself doesn't persist either, same goes for WB setting. That is real pain to set everything up every time i need to use this app.

Same happens when using obs plugin (except it remembers WB setting), but it also seems like it doesn't work in full range when using hardware acceleration, image have much less dynamic range. Also it doesn't show how to control camera settings from PC thru USB, on your main webpage I only found guide for wifi connection.

Auto-focus doesn't seem to work in obs plugin.

iPhone 7 front camera.

**Comment by aramg** [comment]
Closing in favor of #151 

DroidCam OBS and the iOS versions should support camera parameter restoration (with the Pro upgrade).
Note that front cameras usually don't support auto-focus.

The remote controls require Wifi, even if the main video connection is happening over USB. This is already fixed in the new PC client (Windows only) and will become more broadly available in the near future.
