### ISSUE TITLE
Audio only feature without activating cam, mic only on OBS

### ISSUE THREAD

**Issue by jadewong1011** [dev47apps/droidcam#224]
I am trying to do a setup where I use one android device as the mic and the other as the camera. While I can run both with camera and mic on OBS, the power consumption is profound. Also, streaming the data causes connection issues where an audio connection would require less bandwidth. Thank you.

**Comment by AmmarHaddadi** [comment]
Hi , you can use mic only by following this : 

1. start droidcam on your android device
2. run this command in your terminal (I am assuming that you did `sudo ./install-sound` before): `droidcam-cli -a <phone ip here> <phone port here>` 
> example : `droidcam-cli -a 192.168.0.9 4747`
3. run this to load the microphone into pulseaudio (making it show up as a microphone (I think you have to do it every time)): `pacmd load-module module-alsa-source source_properties=device.description=DroidCam device=hw:Loopback,1,0` 

if you face any problem you can read this on their official website : https://www.dev47apps.com/droidcam/linux/

**Comment by aramg** [comment]
To add to the above suggestion, with _DroidCam OBS_ an audio-only mode isn't supported but it is in the feature request list.

The current recommendation is to turn down video (use Low video quality and 640x480 resolution) which will significantly reduce the bandwidth requirements. The app architecture relies heavily on video being active before anything else, a mic-only option is considered an insignificant use-case due to the lower quality of phone mics.

Closing this an unrelated to the regular droidcam apps.
